apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: PLACEHOLDER_AZURE_CONTAINER_REGISTRY.azurecr.io/as6-2_osso_user_service:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_CONNECTION_STRING
            - name: RabbitMQ
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: RABBITMQ
            - name: Auth__Domain
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AUTH0_DOMAIN
            - name: Auth__Audience
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AUTH0_AUDIENCE
            - name: Test__Email
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: TEST_EMAIL
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: user-service
  type: ClusterIP
