name: Deploy to AKS with Kubeconfig

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Write Kubeconfig to File
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        echo "$KUBECONFIG" > kubeconfig.yaml
        export KUBECONFIG=$(pwd)/kubeconfig.yaml
        echo "KUBECONFIG set to $(pwd)/kubeconfig.yaml"
        kubectl --kubeconfig=$(pwd)/kubeconfig.yaml

    - name: Verify kubectl connection to AKS
      run: |
        kubectl --kubeconfig=$(pwd)/kubeconfig.yaml config view
        kubectl --kubeconfig=$(pwd)/kubeconfig.yaml get nodes

    - name: Log in to ACR
      run: |
        echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Prepare Deployment File
      run: |
        IMAGE_TAG=${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/as6-2_osso_user_service:${{ github.sha }}
        sed -i "s@\\${{ secrets.AZURE_CONTAINER_REGISTRY }}@${{ secrets.AZURE_CONTAINER_REGISTRY }}@g" deployment.yaml
        sed -i "s@\\${{ github.sha }}@${{ github.sha }}@g" deployment.yaml

    - name: Deploy to AKS
      run: |
        kubectl --kubeconfig=$(pwd)/kubeconfig.yaml apply -f deployment.yaml --validate=false
        kubectl --kubeconfig=$(pwd)/kubeconfig.yaml rollout status deployment/user-service
